# Generated by Django 6.0.8 on 2026-09-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohort", "0003_enrolment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_roles",
                to="cohort.role",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="cohort.cohort",
                verbose_name="coorte",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="cohort.moodleuser",
                verbose_name="usuário",
            ),
        ),
    ]
