# Generated by Django 5.2.10 on 2026-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrador", "0011_alter_solicitacao_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="campus_sigla",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="campus"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="tipo",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="tipo de diário",
            ),
        ),
    ]
