# Generated by Django 6.0.4 on 2026-04-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrador", "0013_alter_ambiente_url_alter_solicitacao_operacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambiente",
            name="active",
        ),
        migrations.RemoveField(
            model_name="ambiente",
            name="token",
        ),
        migrations.AddField(
            model_name="ambiente",
            name="local_suap_active",
            field=models.BooleanField(default=True, verbose_name="local_suap ativo?"),
        ),
        migrations.AddField(
            model_name="ambiente",
            name="local_suap_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="token local_suap"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ambiente",
            name="tool_sga_active",
            field=models.BooleanField(default=True, verbose_name="tool_sga ativo?"),
        ),
        migrations.AddField(
            model_name="ambiente",
            name="tool_sga_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="token tool_sga"),
            preserve_default=False,
        ),
    ]
