### No VSCode, instale o plugin "REST Client" e veja a mágica ocorer :)
### Pressione Ctrl + Alt + R, ou "Send Request", para executar cada request


### Apenas os atributos os obrigatórios
GET http://localhost:8091/api/baixar_notas/?campus_sigla=ZL&diario_id=4 HTTP/1.1
Authentication: Token changeme


### Apenas os atributos os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "campus":     {"id": 1,     "sigla":  "NC",                         "descricao": "CAMPUS NC" },
    "curso":      {"id": 22,    "codigo": "999999",                     "nome":      "AAAA"      },
    "componente": {"id": 333,   "sigla":  "TEC.1234",                   "descricao": "BBBB"      },
    "turma":      {"id": 4444,  "codigo": "20262.6.999999.TEC.1234.1E"                           },
    "diario":     {"id": 55555, "sigla":  "TEC.1234",                   "situacao":  "Aberto"    }
}

### Apenas os atributos os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "campus":     {"id": 1,     "sigla":  "NC",                         "descricao": "CAMPUS NC" },
    "curso":      {"id": 22,    "codigo": "999999",                     "nome":      "AAAA"      },
    "componente": {"id": 333,   "sigla":  "TEC.1234",                   "descricao": "BBBB"      },
    "turma":      {"id": 4444,  "codigo": "20262.6.999999.TEC.1234.1E"                           },
    "diario":     {"id": 55555, "sigla":  "TEC.1234",                   "situacao":  "Aberto"    },

    "alunos": [{"matricula": "20260000000001", "email": "", "email_secundario": "aluno1@gmail.com", "situacao": "ativo", "nome": "aluno um", "situacao_diario": "ativo"}]
}


### Todos os atributos nulos, exceto de usuários
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",

        "descricao": null,
        "descricao_historico": null,
        "titulo_certificado_masculino": null,
        "titulo_certificado_feminino": null,
        "ch_total": null,
        "ch_aula": null,
        "programa": null,
        "autoinstrucional": null,
        "autoinscricao": null,
        "conteudo": null,
        "modalidade": null,
        "restricoes": null
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": null,
        "periodo": null,
        "optativo": null,
        "qtd_avaliacoes": null,
        "descricao_historico": null,
        "is_seminario_estagio_docente": null,
        "ch_presencial": null,
        "ch_pratica": null,
        "ch_extensao": null,
        "ch_pcc": null,
        "ch_visita_tecnica": null,
        "ch_semanal_1s": null,
        "ch_semanal_2s": null
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": null,
        "data_fim": null,
        "gerar_matricula": null,
        "modelo_padrao": null,
        "nota_minima": null,
        "completude_minima": null
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": null,
        "situacao": null,
        "descricao": null,
        "descricao_historico": null
    }
}


### Todos os atributos preenchidos, exceto de usuários
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        }
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "autoinscricao": {
        "estrangeiros": true,
        "tecnicos_administrativos": true,
        "docentes": true,
        "prestadores": true,
        "alunos": true,
        "niveis_ensino": [
            "Graduação", "Ensino Médio", "Pós-Graduação"
        ],
        "modalidades": [
            "Tecnologia", "Artes"
        ],
        "campi": [
            "CNAT", "ZL"
        ],
        "cursos": [
            "Tecnologia em Desenvolvimento de Software",
            "Tecnologias de Sistemas para Internet"
        ]
    }
}


### Todos os atributos preenchidos, dos usuários apenas os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "alunos": [
        {
            "matricula": "20260000000001",
            "email": "",
            "email_secundario": "aluno1@gmail.com",
            "situacao": "ativo",
            "nome": "aluno um",
            "situacao_diario": "ativo"
        }
    ],
    "professores": [
        {
            "nome": "Professor principal",
            "tipo": "Principal",
            "email": "professor.principal@ifrn.edu.br",
            "email_secundario": "professor.principal@escolar.ifrn.edu.br",
            "login": "123456",
            "status": "ativo"
        },
        {
            "nome": "Professor formador",
            "tipo": "Formador",
            "email": "professor.formador@ifrn.edu.br",
            "email_secundario": "professor.formador@escolar.ifrn.edu.br",
            "login": "123457",
            "status": "ativo"
        },
        {
            "nome": "Professor tutor",
            "tipo": "Tutor",
            "email": "professor.tutor@ifrn.edu.br",
            "email_secundario": "professor.tutor@escolar.ifrn.edu.br",
            "login": "123458",
            "status": "ativo"
        },
        {
            "nome": "Professor mediador",
            "tipo": "Mediador",
            "email": "professor.mediador@ifrn.edu.br",
            "email_secundario": "professor.mediador@escolar.ifrn.edu.br",
            "login": "123459",
            "status": "inativo"
        }
    ],
    "equipe": [
        {
            "nome": "Coordenador de Curso 1",
            "tipo": "Coordenador de Curso",
            "email": "coordenador.curso1@ifrn.edu.br",
            "email_secundario": "coordenador.curso1@escolar.ifrn.edu.br",
            "login": "345678",
            "status": "ativo"
        },
        {
            "nome": "Coordenador de Curso 2",
            "tipo": "Coordenador de Curso",
            "email": "coordenador.curso2@ifrn.edu.br",
            "email_secundario": "coordenador.curso2@escolar.ifrn.edu.br",
            "login": "345679",
            "status": "ativo"
        }
    ],
    "sincrono": true
}




### Suspende o aluno acima
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "sincrono": true
}


### Todos os atributos preenchidos, inclusive dos usuários
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 33,
        "codigo": "888888",
        "nome": "CCCC",
        "descricao": "CCCC",

        "descricao_historico": "CCCC",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": false,
        "autoinscricao": false,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 444,
        "sigla": "TEC.4444",
        "descricao": "DDDD",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "DDDD",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.888888.TEC.4444.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 888888,
        "sigla": "TEC.4444",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "DDDDDD",
        "descricao_historico": "DDDDDD"
    },
    "alunos": [
        {
            "matricula": "20260000000001",
            "email": "",
            "email_secundario": "aluno1@gmail.com",
            "situacao": "ativo",
            "nome": "Aluno Um",
            "situacao_diario": "ativo",

            "tipo_usuario": "Aluno",
            "eh_servidor": false,
            "eh_aluno": true,
            "eh_prestador": false,
            "eh_usuarioexterno": false,
            "eh_docente": false,
            "eh_tecnico_administrativo": false,

            "nome_usual": "Um Aluno",
            "nome_registro": "Aluno Um",
            "nome_social": "Alummini Hum",
            "data_de_nascimento": "1999-09-09",
            "sexo": "M",
            "cpf": "00000000191",
            "passaporte": "32165497",
            "eh_estrangeiro": false,

            "email_google_classroom": "aluno.um@escolar.ifrn.edu.br",
            "email_academico": "um.aluno@academico.ifrn.edu.br",

            "programa": "UAB",
            "ingresso_periodo": "9999.9",
            "outras_matriculas": [
                {
                    "identificacao": "9999999999AAAA001",
                    "curso": {
                        "id": 99999,
                        "codigo": "99999",
                        "nome": "Um nome de curso pode ser extremamente longo, contendo muitos caracteres, como este exemplo aqui, e na verdade até pior"
                    }
                }
            ],
            "polo": {
                "id": 1,
                "sigla": "NC",
                "descricao": "Polo UAB de NC"
            }
        },
        {
            "matricula": "20260000000002",
            "email": "",
            "email_secundario": "aluno2@gmail.com",
            "situacao": "ativo",
            "nome": "Aluno Dois",
            "situacao_diario": "ativo",

            "tipo_usuario": "Aluno",
            "eh_servidor": false,
            "eh_aluno": true,
            "eh_prestador": false,
            "eh_usuarioexterno": false,
            "eh_docente": false,
            "eh_tecnico_administrativo": false,

            "nome_usual": "Dois Aluno",
            "nome_registro": "Aluno Dois",
            "nome_social": "Alummini Dos",
            "data_de_nascimento": "1999-09-09",
            "sexo": "M",
            "cpf": null,
            "passaporte": "789456132",
            "eh_estrangeiro": true,

            "email_google_classroom": "aluno.dois@escolar.ifrn.edu.br",
            "email_academico": "dois.aluno@academico.ifrn.edu.br",

            "programa": "UAB",
            "ingresso_periodo": "9999.9",
            "outras_matriculas": [
                {
                    "identificacao": "9999999999AAAA001",
                    "curso": {
                        "id": 99999,
                        "codigo": "99999",
                        "nome": "Um nome de curso pode ser extremamente longo, contendo muitos caracteres, como este exemplo aqui, e na verdade até pior"
                    }
                }
            ],
            "polo": {
                "id": 1,
                "sigla": "NC",
                "descricao": "Polo UAB de NC"
            }
        }
    ],
    "sincrono": true
}


### Curso com auto-inscrição
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 123,
        "codigo": "123456",
        "nome": "UDTUDT",
        "descricao": "UDT",

        "descricao_historico": "UDT",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            }
        ]
    },
    "componente": {
        "id": 123,
        "sigla": "TEC.123",
        "descricao": "UDT",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "UDT",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.1.UDT.TEC.123.AI",
        "data_inicio": "2026-01-01",
        "data_fim": "2026-12-31",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 123456,
        "sigla": "TEC.123",
        "tipo": "minicurso",
        "situacao": "Aberto",
        "descricao": "UDT",
        "descricao_historico": "UDT"
    },
    "sincrono": true
}
