# -*- coding: utf-8 -*-
from settings import sessions as _sessions
from settings.apps import *  # noqa
from settings.caches import *  # noqa
from settings.databases import *  # noqa
from settings.developments import *  # noqa
from settings.emails import *  # noqa
from settings.internationalizations import *  # noqa
from settings.loggings import *  # noqa
from settings.middlewares import *  # noqa
from settings.observabilities import *  # noqa
from settings.project import *  # noqa
from settings.routings import *  # noqa
from settings.securities import *  # noqa
from settings.templates import *  # noqa

for _name in dir(_sessions):
    if _name.isupper():
        globals()[_name] = getattr(_sessions, _name)
del _name
del _sessions

# Generated by 'django-admin startproject' using Django 5.0.2.
# https://docs.djangoproject.com/en/5.0/fhowto/deployment/checklist/
# https://docs.djangoproject.com/en/5.0/topics/settings/
# https://docs.djangoproject.com/en/5.0/ref/settings/
