[pytest]
DJANGO_SETTINGS_MODULE = settings  # ajuste para o módulo correto
testpaths = .                      # ou liste só os apps, se quiser
python_files = tests.py test_*.py *_tests.py
python_classes = *TestCase
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
