[pytest]
# ajuste para o módulo correto
DJANGO_SETTINGS_MODULE = settings
# ou liste só os apps, se quiser
testpaths = .
python_files = tests.py test_*.py *_tests.py
python_classes = *TestCase
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
