name: Deploy

on:
  release:
    types: [published]

permissions: {}

jobs:

  deploy:
    environment:
      name: ${{ startsWith(github.ref, 'refs/tags/') && 'production' || 'test' }}
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ vars.RUNNER_LABEL || 'self-hosted' }}
    needs: build-and-push
    steps:
      - name: Pull and restart service
        run: |
          cd ${{ vars.DEPLOY_DOCKER_PATH }}
          date
          # sed -i 's|ctezlifrn/avaintegrador:.*|ctezlifrn/avaintegrador:${{ github.ref_name }}|g' docker-compose.yml && \
          # docker compose pull ${{ vars.DOCKER_SERVICE_NAME }}
          # docker compose down ${{ vars.DOCKER_SERVICE_NAME }}
          # docker compose up -d ${{ vars.DOCKER_SERVICE_NAME }}
          # timeout 60s docker compose logs -f ${{ vars.DOCKER_SERVICE_NAME }} || true
